dep('mysql installed'){
  requires 'mysql.managed', 'mysql server installed', 'mysql seeded with users'
}

dep('mysql.managed') {
  installs { via :apt, 'mysql-client', 'libmysqlclient-dev', 'libmysql-ruby' }
}

dep('mysql server installed') {
  requires 'preseeding directory', 'mysql server seeded', 'mysql server configured', 'mysql-server.managed', 'mysql configured', 'mysql has blank root password'
  after {
    shell "sudo service mysql restart"
  }
}

dep('preseeding directory') {
  met? {
    shell? "sudo stat /var/cache/local/preseeding"
  }

  meet {
    sudo "mkdir -p /var/cache/local/preseeding"
    sudo "chmod 0755 /var/cache/local/preseeding"
  }
}

dep('mysql server seeded') {
  met? { shell? "sudo stat /var/cache/local/preseeding/mysql-server.seed" }
  meet {
    render_erb('mysql/mysql-server.seed.erb', :to => '/var/cache/local/preseeding/mysql-server.seed', :sudo => true)
    sudo "debconf-set-selections /var/cache/local/preseeding/mysql-server.seed"
  }
}

dep('mysql server configured') {
  met? { shell?("sudo grep 'Generated by babushka' /etc/mysql/debian.cnf", :sudo => true) }
  meet {
    render_erb 'mysql/debian.cnf.erb', :to => '/etc/mysql/debian.cnf', :sudo => true
    sudo "chmod 0600 /etc/mysql/debian.cnf"
  }
}

dep('mysql-server.managed') {
  installs { via :apt, 'mysql-server'}
  provides []
}

dep('mysql configured') {
  met? { shell?("sudo grep 'Generated by babushka' /etc/mysql/my.cnf") }

  meet {
    render_erb "mysql/my.cnf.erb", :to => '/etc/mysql/my.cnf', :sudo => true
    sudo "chmod 0644 /etc/mysql/my.cnf"
  }
}

dep('mysql has blank root password') {
  met? { shell? "/usr/bin/mysql -u root -e 'show databases;'" }
  meet {
    shell "/usr/bin/mysqladmin -u root password \"\""
  }
}

dep('mysql seeded with users') {
  def grants_path
    '/etc/mysql' / 'mysql_grants.sql'
  end
  
  met? { 
    shell?("sudo grep 'Generated by babushka' #{grants_path}") &&
    shell?("/usr/bin/mysql -u root -e 'SELECT user FROM mysql.user;' | grep 'ubuntu'")
  }
  meet {
    render_erb "mysql/mysql_grants.sql.erb", :to => grants_path, :sudo => true
    sudo "chmod 0644 #{grants_path}"
    shell "/usr/bin/mysql -u root '' < #{grants_path}"
  }
}
