dep('mysql installed'){
  requires 'mysql.managed', 'mysql server installed'
}

dep('mysql.managed') {
  installs { via :apt, 'mysql-client', 'libmysqlclient-dev', 'libmysql-ruby' }
}

dep('mysql server installed') {
  requires 'preseeding directory', 'mysql server seeded', 'mysql server configured', 'mysql-server.managed', 'mysql configured', 'mysql has blank root password'
  after {
    shell "sudo service mysql restart"
  }
}

dep('preseeding directory') {
  met? {
    shell? "sudo stat /var/cache/local/preseeding"
  }

  meet {
    sudo "mkdir -p /var/cache/local/preseeding"
    sudo "chmod 0755 /var/cache/local/preseeding"
  }
}

dep('mysql server seeded') {
  met? { shell? "sudo stat /var/cache/local/preseeding/mysql-server.seed" }
  meet {
    render_erb('mysql/mysql-server.seed.erb', :to => '/var/cache/local/preseeding/mysql-server.seed', :sudo => true)
    sudo "debconf-set-selections /var/cache/local/preseeding/mysql-server.seed"
  }
}

dep('mysql server configured') {
  met? { shell?("sudo grep 'Generated by babushka' /etc/mysql/debian.cnf", :sudo => true) }
  meet {
    render_erb 'mysql/debian.cnf.erb', :to => '/etc/mysql/debian.cnf', :sudo => true
    sudo "chmod 0600 /etc/mysql/debian.cnf"
  }
}

dep('mysql-server.managed') {
  installs { via :apt, 'mysql-server'}
  provides []
}

dep('mysql configured') {
  met? { shell?("grep 'Generated by babushka' /etc/mysql/my.cnf", :sudo => true) }

  meet {
    render_erb "mysql/my.cnf.erb", :to => '/etc/mysql/my.cnf', :sudo => true
    sudo "chmod 0644 /etc/mysql/my.cnf"
  }
}

dep('mysql has blank root password') {
  met? { shell? "/usr/bin/mysql -u root -e 'show databases;'" }
  meet {
    shell "/usr/bin/mysqladmin -u root password \"\""
  }
}
