dep('postgresql installed'){
  requires 'sysctl shared memory configured', 'postgres.managed', 'postgres configured'
}

dep 'postgres.managed', :version do
  version.default('9.1')

  requires {
    on :apt, 'set.locale', 'postgres.ppa'
    on :brew, 'set.locale'
  }
  installs {
    via :apt, ["postgresql-#{owner.version}", "libpq-dev", 'postgresql-client']
    via :brew, "postgresql"
  }
  provides "psql ~> #{version}.0"
end

dep 'postgres access' do
  requires 'postgres.managed', 'user exists'
  met? { !sudo("echo '\\du' | #{which 'psql'}", :as => 'postgres').split("\n").grep(/^\W*\b#{var :username}\b/).empty? }
  meet { sudo "createuser -SdR #{var :username}", :as => 'postgres' }
end

dep 'pg.gem' do
  requires 'postgres.managed'
  provides []
end

dep 'postgres.ppa' do
  adds 'ppa:pitti/postgresql'
end

dep('postgres configured', :version) {
  version.default('9.1')

  def postgres_dir
    "/etc/postgresql/#{version}/main"
  end

  def max_connections
    255
  end

  met? {
    shell?("grep 'Generated by babushka' #{postgres_dir}/postgresql.conf", :sudo => true) &&
    shell?("grep 'Generated by babushka' #{postgres_dir}/pg_hba.conf", :sudo => true)
  }

  meet {
    render_erb("postgres/pg_hba.conf.erb", :to => "#{postgres_dir}/pg_hba.conf", :sudo => true, :perms => '600', :as => 'postgres')
    render_erb("postgres/postgresql.conf.erb", :to => postgres_dir / 'postgresql.conf', :sudo => true, :perms => '600', :as => 'postgres')
    shell("chown postgres:postgres #{postgres_dir}/pg_hba.conf", :sudo => true)
    shell("chown postgres:postgres #{postgres_dir}/postgresql.conf", :sudo => true)
  }

  after {
    log_shell "Restarting postgres", "service postgresql restart", :sudo => true
  }
}

dep('sysctl shared memory configured') {
  met? {
    shell?("grep '^kernel.shmmax' /etc/sysctl.d/30-postgresql-shm.conf") &&
    shell?("grep '^kernel.shmall' /etc/sysctl.d/30-postgresql-shm.conf")
  }

  meet {
    change_line("#kernel.shmmax = 33554432", "kernel.shmmax = 134217728", "/etc/sysctl.d/30-postgresql-shm.conf")
    change_line("#kernel.shmall = 2097152", "kernel.shmall = 32768", "/etc/sysctl.d/30-postgresql-shm.conf")
  }
}
