dep('postgresql installed'){
  requires 'postgres.managed', 'postgres configured', 'sysctl shared memory configured', 'postgres test users exist', 'postgres on startup'
}

dep 'postgres.managed', :version do
  version.default('9.1')

  requires {
    on :apt, 'set.locale', 'postgres.ppa'
    on :brew, 'set.locale'
  }
  installs {
    via :apt, ["postgresql-#{owner.version}", "libpq-dev", 'postgresql-client']
    via :brew, "postgresql"
  }
  provides "psql ~> #{version}.0"
end

dep 'postgres access' do
  requires 'postgres.managed', 'user exists'
  met? { !sudo("echo '\\du' | #{which 'psql'}", :as => 'postgres').split("\n").grep(/^\W*\b#{var :username}\b/).empty? }
  meet { sudo "createuser -SdR #{var :username}", :as => 'postgres' }
end

dep('postgres test users exist') {
  users = ['rails', 'ubuntu']

  met? {
    users.all? do |user|
      !sudo("echo '\\du' | #{which 'psql'}", :as => 'postgres').split("\n").grep(/^\W*\b#{user}\b/).empty?
    end
  }

  meet {
    users.each do |user|
      unless sudo("echo '\\du' | #{which 'psql'}", :as => 'postgres').split("\n").grep(/^\W*\b#{user}\b/).empty?
        sudo "dropuser --username postgres #{user}", :as => 'postgres'
      end
      sudo "createuser --no-password --superuser #{user}", :as => 'postgres'
    end
  }
}

dep 'pg.gem' do
  requires 'postgres.managed'
  provides []
end

dep 'postgres.ppa' do
  adds 'ppa:pitti/postgresql'
end

dep('postgres configured', :version) {
  version.default('9.1')

  def postgres_dir
    "/etc/postgresql/#{version}/main"
  end

  def max_connections
    255
  end

  met? {
    shell?("grep 'Generated by babushka' #{postgres_dir}/postgresql.conf", :sudo => true) &&
    shell?("grep 'Generated by babushka' #{postgres_dir}/pg_hba.conf", :sudo => true)
  }

  meet {
    render_erb("postgres/pg_hba.conf.erb", :to => "#{postgres_dir}/pg_hba.conf", :sudo => true, :perms => '600', :as => 'postgres')
    render_erb("postgres/postgresql.conf.erb", :to => postgres_dir / 'postgresql.conf', :sudo => true, :perms => '600', :as => 'postgres')
    shell("chown postgres:postgres #{postgres_dir}/pg_hba.conf", :sudo => true)
    shell("chown postgres:postgres #{postgres_dir}/postgresql.conf", :sudo => true)
  }

  after {
    log_shell "Restarting postgres", "service postgresql restart", :sudo => true
  }
}

dep('sysctl shared memory configured') {
  met? {
    shell?("grep 'Generated by babushka' /etc/sysctl.d/30-postgresql-shm.conf", :sudo => true)
  }

  meet {
    render_erb "postgres/30-shared-memory.conf.erb", :to => "/etc/sysctl.d/30-postgresql-shm.conf", :sudo => true
    sudo "sysctl -w kernel.shmmax=35512320"
    sudo "sysctl -w kernel.shmall=34680"
  }
}

dep('postgres on startup') {

}